# Generated by Django 4.1 on 2022-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.FileField(default='', upload_to='static')),
                ('detail', models.IntegerField()),
            ],
        ),
    ]
