# Generated by Django 4.1 on 2022-09-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_book',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=122)),
                ('book', models.FileField(default='', upload_to='books')),
            ],
        ),
        migrations.DeleteModel(
            name='upload_file',
        ),
    ]
