# Generated by Django 4.1 on 2022-09-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_upload_book_delete_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_book',
        ),
    ]
