# Generated by Django 4.1 on 2022-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0003_delete_upload_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file2', models.FileField(upload_to='')),
            ],
        ),
    ]
